theme: jekyll-theme-architect
title: A Scrupulous Look At the World !!!
description : Hi! I am a Theoretical Physics student. I am trying to rationalise world around me starting from the Postulates of Quantum Mechanics.
